language: node_js
node_js:
- '4.2'
branches:
  only:
    - master
deploy:
  provider: heroku
  api_key:
    secure: FdER0hwtU+v4RyTKcVlzCkdTUxEt6R98ODqmIuGXXHL9nSoiKEt9XFIZS759N/HfTyN7m+INKcFkSDcbJCQg4ZoYXUxhx2/ReYEjy6gw4Ajboo3jhxOmiWRIwCbaCqhTsWAcohs9EfeGzOURZDYhxaIdOOhPT+uezaubeJNm+v2rz76nfmySXJuaAFNXpurIZ26fL47rSP+1J2O4/xWiD9ouF7kcYnaK4U362ro4sLtp9HggFcGs1/fVRrd/wtA3eNKefzeaqzcESiJSU9UgG14AX/sXjIVoRbLJc/NRyqUUVxSamiTj43zk+7lLBsahl8lV5/HM360jO1NJza0ftGOtjSGQhhywiSUYMs9L/FJBcIwG6xnWKErlzlIYo9gE0Q5psjVCD8ilGprD+9b5IMjXGsQJ5MEx5ZJYvN4GiydD8PZgCz20vP42X5JnaT7aokivgV3U0W78gvM5sjgPCEHwOd4mk/yuzL5vFGJMYQxuePLMZtLJTaC8l+63sbO/6B+YSOU1k0RF6w0pawMHcT5qWLnZG13cHToSkyji7ol71MVdbIWmO57q+ZqWwAsBKD+Kc+yjeNoLcrUj/ZBEKGc6/oSLLxW2CEzsp2/Ibomwbq4BiFvsq/ml2aZN3mxm1MBOzXRfeZjHg1BSnS+CSpeKD1LK7QaRwhtNIE6AHXE=
  app: helpmargery
  on:
    repo: marxian/helpmargery
notifications:
  slack:
    secure: QikvdGXzL3nIfmrcPImoP45L7PB4M30M9vFH6qVimcFg4JtYjjofy6ht5Cy74I6Fti1pd6d2oXNLL9YQKP1gbYEVz2HlQtMPsCeO96Q9ROqLLwSdUuoRzHvRqh9F90ccwOoawd3tN0I1M3aBDILpm7kR5waruJQUtrWS0IY5xSHWnUzbVHIslVCfHy/I1Dt584G1ECugsmATL54p/bzdVufOVofPV3Qs9mRPkYw34jXIgvpffa8yujmll/ONzAp3OujfJUjeDdN+rlRacfiWfNDF8kSqpDOctebkTVZC17ONIlYqNNVap7I82tHQtaH5tuww7zPRUeU2WFYtldj7Z1vIwojPMa/3+/6HmozrKT+bPrLEdVY3Ij2Ftr2gj353oXunS0ywTlLhL1Y3+G5xngB1RxYDScRQyXFO6qYjQaElj740tmsOO/5fElqpV/s8gHQ6d4wiljokA07cK0uZaN7NqVlnVKDv1iHKao03wo7XMKF2MZ2+2vCSiwUQcrm6Ml/qBdN+hPfsfxYIHfYZwSwr4z+CbufRJtzmJCJRszuPgVY2bqPPorjaWHLz7BWClJxuHUNxRGVD1QJvaaQj0TraKW5aC0L9UEWAcsaki+wur97noDajcuzSp1EmPbwIM8qwctbxsdplTc7Odfm6pp4bTHqx0vIEtn8t4gsF/1Y=
